name: drone
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - librosa
  - numpy
  - scikit-learn
  - matplotlib
  - jupyter
  - ipykernel
  - joblib
  - kaggle
  - pip
  - pip:
    # Let pip handle the TensorFlow installation. It will automatically
    # fetch the correct version for your OS (macOS or Linux).
    - tensorflow
    - soundfile