name: drone
channels:
  - conda-forge
  - defaults
  - nvidia/label/main

dependencies:
  - python=3.10
  - cudatoolkit=11.8
  - cudnn=8.9

  - pip
  - ipykernel
  - jupyter

  # 科学计算尽量 conda（稳定）
  - numpy<2.0
  - scipy
  - scikit-learn
  - matplotlib
  - joblib

  # 音频相关改 pip（避免 conda 包名/依赖问题）
  - pip:
      - tensorflow==2.14.0
      - keras==2.14.0
      - librosa
      - soundfile