name: drone
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - librosa
  - numpy
  - scikit-learn
  - matplotlib
  - jupyter
  - ipykernel
  - joblib
  - kaggle
  - pip
  # Conda Forge's cudatoolkit is often the most reliable way to manage GPU drivers
  - cudatoolkit=11.8.0
  - pip:
    # Use the standard tensorflow package for Linux
    - tensorflow==2.16.*
    - soundfile